// ─── Design tokens ────────────────────────────────────────────────────────────
export const T = {
  bg:        "#090909",
  surface:   "#111111",
  surface2:  "#161616",
  border:    "#1f1f1f",
  border2:   "#2a2a2a",
  text:      "#ffffff",
  textSub:   "#888888",
  textMuted: "#444444",
  accent:    "#F5C518",
  accentDim: "#F5C51822",
  green:     "#22c55e",
  red:       "#ef4444",
  mono:      "'IBM Plex Mono', monospace",
  sans:      "'Inter', sans-serif",
};

// ─── Estilos de layout global ─────────────────────────────────────────────────
export const S = {
  app:         { display:"flex", minHeight:"100vh", background:T.bg, fontFamily:T.sans, color:T.text },
  sidebar:     { position:"fixed", top:0, left:0, height:"100vh", background:T.surface, borderRight:`1px solid ${T.border}`, display:"flex", flexDirection:"column", zIndex:100, transition:"width .26s cubic-bezier(.4,0,.2,1)", overflow:"hidden" },
  sidebarLogo: { display:"flex", alignItems:"center", gap:12, padding:"18px 14px 14px", borderBottom:`1px solid ${T.border}`, flexShrink:0, cursor:"pointer", userSelect:"none", minHeight:68 },
  logoText:    { fontSize:16, fontWeight:800, color:T.text, letterSpacing:-.4, whiteSpace:"nowrap" },
  nav:         { flex:1, padding:"8px", display:"flex", flexDirection:"column", gap:2, overflowY:"auto" },
  navItem:     { display:"flex", alignItems:"center", gap:11, padding:"10px 11px", borderRadius:10, background:"transparent", border:"none", color:T.textMuted, cursor:"pointer", transition:"background .15s, color .15s", fontSize:13, fontFamily:T.sans, fontWeight:500, width:"100%", whiteSpace:"nowrap" },
  navActive:   { background:T.accent, color:"#000", fontWeight:700, boxShadow:`0 4px 16px ${T.accent}44` },
  main:        { flex:1, minWidth:0, transition:"margin-left .26s cubic-bezier(.4,0,.2,1)" },
  mobileBar:   { position:"fixed", top:0, left:0, right:0, height:56, background:T.surface, borderBottom:`1px solid ${T.border}`, display:"flex", alignItems:"center", gap:12, padding:"0 16px", zIndex:100 },
  mobileCdi:   { marginLeft:"auto", fontSize:11, color:T.accent, fontFamily:T.mono, background:T.accentDim, padding:"4px 10px", borderRadius:20 },
  hamburger:   { background:"transparent", border:"none", color:T.textSub, cursor:"pointer", display:"flex", alignItems:"center", padding:4, borderRadius:8, transition:"color .15s" },
  drawerOverlay:{ position:"fixed", inset:0, background:"rgba(0,0,0,.75)", backdropFilter:"blur(6px)", zIndex:200, display:"flex" },
  drawer:      { width:280, background:T.surface, borderRight:`1px solid ${T.border}`, height:"100%", display:"flex", flexDirection:"column", padding:"0 0 24px 0", overflowY:"auto" },
  drawerHeader:{ display:"flex", alignItems:"center", justifyContent:"space-between", padding:"18px 16px 14px", borderBottom:`1px solid ${T.border}`, flexShrink:0 },
  drawerItem:  { display:"flex", alignItems:"center", gap:14, padding:"13px 20px", background:"transparent", border:"none", color:"#aaaaaa", cursor:"pointer", fontSize:14, fontFamily:T.sans, fontWeight:500, transition:"background .15s, color .15s", width:"100%", textAlign:"left", position:"relative" },
  drawerItemActive:{ background:T.accentDim, color:T.accent, fontWeight:700 },
  drawerActiveDot: { position:"absolute", right:16, width:6, height:6, borderRadius:50, background:T.accent },
  alertBanner: { position:"fixed", top:0, left:0, right:0, background:"#1a1200", borderBottom:`1px solid ${T.accent}33`, padding:"9px 20px", display:"flex", alignItems:"center", gap:10, zIndex:300, color:T.accent, fontFamily:T.mono, fontSize:11 },
  toast:       { position:"fixed", padding:"13px 20px", borderRadius:12, border:"1px solid", fontSize:13, fontFamily:T.mono, zIndex:500, boxShadow:"0 8px 32px rgba(0,0,0,.6)" },
};

// ─── Estilos de página e componentes ─────────────────────────────────────────
export const P = {
  root:        { maxWidth:1100, margin:"0 auto" },
  pageHeader:  { display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:32, flexWrap:"wrap", gap:16 },
  pageTitle:   { fontSize:30, fontWeight:800, color:T.text, letterSpacing:-1, lineHeight:1.1 },
  pageSub:     { fontSize:13, color:T.textMuted, marginTop:6 },
  kpiRow:      { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))", gap:12, marginBottom:24 },
  kpiCard:     { background:T.surface, border:`1px solid ${T.border}`, borderRadius:14, padding:"18px 20px" },
  kpiLabel:    { fontSize:10, color:T.textMuted, textTransform:"uppercase", letterSpacing:1.5, fontFamily:T.mono },
  kpiValue:    { fontSize:22, fontWeight:800, letterSpacing:-.5, fontFamily:T.mono },
  chartCard:   { background:T.surface, border:`1px solid ${T.border}`, borderRadius:14, padding:"20px 22px" },
  chartTitle:  { fontSize:10, fontWeight:700, color:T.textMuted, textTransform:"uppercase", letterSpacing:1.6, fontFamily:T.mono },
  filterRow:   { display:"flex", flexWrap:"wrap", gap:10, marginBottom:20, alignItems:"center" },
  search:      { background:T.surface2, border:`1px solid ${T.border2}`, borderRadius:9, color:T.text, padding:"10px 14px", fontFamily:T.mono, fontSize:13, outline:"none", width:210 },
  chip:        { background:T.surface, border:`1px solid ${T.border2}`, borderRadius:20, padding:"6px 14px", color:T.textMuted, fontSize:12, fontFamily:T.mono, cursor:"pointer", transition:"all .15s", whiteSpace:"nowrap" },
  cardGrid:    { display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))", gap:14 },
  invCard:     { background:T.surface, border:`1px solid ${T.border}`, borderRadius:14, padding:"20px", display:"flex", flexDirection:"column", gap:11 },
  metrics:     { display:"grid", gridTemplateColumns:"1fr 1fr", gap:8 },
  metricBox:   { background:T.bg, borderRadius:9, padding:"9px 12px", border:`1px solid ${T.border}` },
  metricLabel: { color:T.textMuted, fontSize:9, textTransform:"uppercase", letterSpacing:1, fontFamily:T.mono },
  metricValue: { color:"#ccc", fontSize:13, fontWeight:600, fontFamily:T.mono, marginTop:4 },
  setCard:     { background:T.surface, border:`1px solid ${T.border}`, borderRadius:14, padding:"22px 24px", marginBottom:14 },
  setTitle:    { fontSize:10, fontWeight:700, color:T.textMuted, textTransform:"uppercase", letterSpacing:1.6, fontFamily:T.mono, marginBottom:18 },
  table:       { width:"100%", borderCollapse:"collapse", fontFamily:T.mono, fontSize:12 },
  th:          { padding:"10px 16px", textAlign:"left", color:T.textMuted, fontWeight:600, fontSize:10, letterSpacing:1.1, textTransform:"uppercase", borderBottom:`1px solid ${T.border}`, whiteSpace:"nowrap" },
  tr:          { borderBottom:`1px solid ${T.border}` },
  td:          { padding:"11px 16px", color:"#aaa", whiteSpace:"nowrap" },
  label:       { display:"block", fontSize:10, color:T.textMuted, textTransform:"uppercase", letterSpacing:1.3, fontFamily:T.mono, marginBottom:7, marginTop:16 },
  input:       { background:T.bg, border:`1px solid ${T.border2}`, borderRadius:9, color:T.text, padding:"11px 14px", fontFamily:T.mono, fontSize:13, outline:"none", width:"100%", boxSizing:"border-box" },
  btn:         { background:T.accent, color:"#000", border:"none", padding:"11px 22px", borderRadius:10, fontFamily:T.sans, fontWeight:700, fontSize:13, cursor:"pointer", display:"inline-flex", alignItems:"center", gap:7 },
  btnSec:      { background:"transparent", border:`1px solid ${T.border2}`, color:T.accent, padding:"10px 16px", borderRadius:10, fontFamily:T.sans, fontWeight:600, fontSize:12, cursor:"pointer", display:"inline-flex", alignItems:"center", gap:7 },
  btnCancel:   { background:"transparent", border:`1px solid ${T.border}`, color:T.textSub, borderRadius:10, padding:"10px 20px", fontFamily:T.sans, fontWeight:600, fontSize:13, cursor:"pointer" },
  iBtn:        { background:"transparent", border:`1px solid ${T.border}`, borderRadius:7, padding:"6px 9px", cursor:"pointer", color:T.textMuted, display:"inline-flex", alignItems:"center", justifyContent:"center" },
  note:        { fontSize:10, color:T.textMuted, marginTop:10, fontFamily:T.mono, fontStyle:"italic" },
  empty:       { textAlign:"center", padding:"56px 24px", color:T.textMuted, background:T.surface, borderRadius:14, border:`1px solid ${T.border}`, fontFamily:T.mono, fontSize:13 },
  pill:        { border:"1px solid", borderRadius:20, padding:"3px 10px", fontSize:11, fontFamily:T.mono },
  toggleBtn:   { background:"transparent", border:"none", color:T.textMuted, borderRadius:7, padding:"7px 16px", fontFamily:T.sans, fontWeight:600, fontSize:12, cursor:"pointer", transition:"all .15s" },
  toggleActive:{ background:T.accent, color:"#000", fontWeight:700 },
  grid2:       { display:"grid", gap:14, marginBottom:18 },
  metaCard:    { background:T.surface, border:`1px solid ${T.accent}33`, borderRadius:14, padding:"18px 20px", marginBottom:24 },
  metaTrack:   { height:6, background:T.surface2, borderRadius:3, overflow:"hidden", marginTop:10 },
  metaFill:    { height:6, background:`linear-gradient(90deg,#c9a020,${T.accent})`, borderRadius:3, transition:"width .6s cubic-bezier(.4,0,.2,1)" },
};

// ─── Estilos de modal ─────────────────────────────────────────────────────────
export const M = {
  overlay:      { position:"fixed", inset:0, background:"rgba(0,0,0,.88)", display:"flex", justifyContent:"center", zIndex:400, backdropFilter:"blur(10px)", padding:16 },
  box:          { background:T.surface, border:`1px solid ${T.border2}`, padding:"28px", maxHeight:"92vh", overflowY:"auto", display:"flex", flexDirection:"column", gap:6 },
  title:        { fontSize:20, fontWeight:800, color:T.text, marginBottom:12, letterSpacing:-.4 },
  typeBtn:      { background:T.bg, border:`1px solid ${T.border2}`, borderRadius:11, padding:"10px 4px", color:T.textMuted, cursor:"pointer", display:"flex", flexDirection:"column", alignItems:"center", gap:4, fontFamily:T.mono, transition:"all .15s" },
  catChip:      { background:T.bg, border:`1px solid ${T.border2}`, borderRadius:7, padding:"7px 13px", color:T.textMuted, fontSize:12, fontFamily:T.mono, cursor:"pointer", transition:"all .15s" },
  catChipActive:{ borderColor:T.accent, color:T.accent, background:T.accentDim },
  irNote:       { background:"#ff000009", border:"1px solid #ef444433", borderRadius:9, padding:"10px 14px", fontSize:11, color:"#f87171", fontFamily:T.mono },
  actions:      { display:"flex", gap:10, justifyContent:"flex-end", marginTop:20 },
};
